name: CI
on:
  push:
    branches:
      - master
  pull_request:

env:
  NODE_VERSION: 17
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: actions/checkout@v2

      - run: yarn install
      - run: yarn lint
      - run: yarn test
      # - uses: codecov/codecov-action@v1
      #   with:
      #     file: ./coverage/clover.xml

  release:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/checkout@v2
      - run: yarn install
      - name: Semantic Release
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
